#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-jupyter_cache
Version  : 0.4.3
Release  : 3
URL      : https://files.pythonhosted.org/packages/49/cd/43a393cd0e5a5019598bf899c3ccfac4b8ac92b6b47d25980a44cc1a3ec3/jupyter-cache-0.4.3.tar.gz
Source0  : https://files.pythonhosted.org/packages/49/cd/43a393cd0e5a5019598bf899c3ccfac4b8ac92b6b47d25980a44cc1a3ec3/jupyter-cache-0.4.3.tar.gz
Summary  : A defined interface for working with a cache of jupyter notebooks.
Group    : Development/Tools
License  : MIT
Requires: pypi-jupyter_cache-bin = %{version}-%{release}
Requires: pypi-jupyter_cache-license = %{version}-%{release}
Requires: pypi-jupyter_cache-python = %{version}-%{release}
Requires: pypi-jupyter_cache-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
Provides: jupyter-cache
Provides: jupyter-cache-python
Provides: jupyter-cache-python3
BuildRequires : pypi(attrs)
BuildRequires : pypi(nbclient)
BuildRequires : pypi(nbdime)
BuildRequires : pypi(nbformat)
BuildRequires : pypi(sqlalchemy)

%description
# jupyter-cache
        
        [![CI Status][travis-badge]][travis-link]
        [![Coverage][coveralls-badge]][coveralls-link]
        [![Documentation Status][rtd-badge]][rtd-link]

%package bin
Summary: bin components for the pypi-jupyter_cache package.
Group: Binaries
Requires: pypi-jupyter_cache-license = %{version}-%{release}

%description bin
bin components for the pypi-jupyter_cache package.


%package license
Summary: license components for the pypi-jupyter_cache package.
Group: Default

%description license
license components for the pypi-jupyter_cache package.


%package python
Summary: python components for the pypi-jupyter_cache package.
Group: Default
Requires: pypi-jupyter_cache-python3 = %{version}-%{release}

%description python
python components for the pypi-jupyter_cache package.


%package python3
Summary: python3 components for the pypi-jupyter_cache package.
Group: Default
Requires: python3-core
Provides: pypi(jupyter_cache)
Requires: pypi(attrs)
Requires: pypi(nbclient)
Requires: pypi(nbdime)
Requires: pypi(nbformat)
Requires: pypi(sqlalchemy)

%description python3
python3 components for the pypi-jupyter_cache package.


%prep
%setup -q -n jupyter-cache-0.4.3
cd %{_builddir}/jupyter-cache-0.4.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1641449935
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-jupyter_cache
cp %{_builddir}/jupyter-cache-0.4.3/LICENSE %{buildroot}/usr/share/package-licenses/pypi-jupyter_cache/ab5a711cce75e49bdbd08bbcb728262e30580e5d
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/jcache

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-jupyter_cache/ab5a711cce75e49bdbd08bbcb728262e30580e5d

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
